version: '3'
services:
  api:
    build:
      context: docker/api
    image: mtaws/python36
    ports:
      - 8080:8080
    volumes:
      - ./src:/app
    working_dir: /app
    environment:
      - DOCKER=1
      - DDB_HOST=http://ddb:8989
      - AWS_SECRET_ACCESS_KEY=''
      - AWS_ACCESS_KEY_ID=''
      - SWAGG_API_KEY=123456
      - API_PREFIX=/api
    command:
      - uwsgi
      - --ini
      - /uwsgi.ini
  nginx:
    build:
      context: docker/nginx
    image: mtaws/nginx
    ports:
      - 80:80
  ddb:
    image: cnadiminti/dynamodb-local
    volumes:
      - dynamo:/dynamodb_local_db
    ports:
      - 8989:8989
    environment:
      - DYNAMODB_PORT=8989
  ddbadmin:
    build:
      context: docker/ddbadmin
    image: mtaws/ddbadmin
    ports:
      - 8001:8001
    command: dynamodb-admin
  sqs:
    image: docker/sqs
    build:
      context: ./docker/sqs
    ports:
      - 9324:9324
      - 9325:9325
  sqsrunner:
    build:
      context: docker/api
    image: mtaws/python36
    volumes:
      - ./src:/app
    working_dir: /app
    environment:
      - DOCKER=1
      - DDB_HOST=http://ddb:8989
      - AWS_SECRET_ACCESS_KEY=''
      - AWS_ACCESS_KEY_ID=''
      - SWAGG_API_KEY=123456
      - API_PREFIX=/api
    command:
      - python
      - /app/local_sqs_runner.py
      - runner
    depends_on:
      - sqs
volumes:
  dynamo:
